name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '7.4']
        composer-lowest: [ '', '--prefer-lowest' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP Action
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: ${{ matrix.php-version }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php~${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php~${{ matrix.php-version }}

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      uses: php-actions/composer@v4
      with:
        composer_version: 1
        args: --prefer-dist
        command: config --global http-basic.repo.magento.com ${{ secrets.mage_user }} ${{ secrets.mage_pw }} && composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer-lowest }}

    - name: Run test suite
      run: composer run-script test
